---
title: "Explore Trigrams (Ger - Fra)"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE)

library(tidyverse, warn.conflicts = F, quietly = T)
library(scales, warn.conflicts = F, quietly = T)
library(glue, warn.conflicts = F, quietly = T)
library(shiny, warn.conflicts = F, quietly = T)
library(plotly, warn.conflicts = F, quietly = T)
library(tidytext, warn.conflicts = F, quietly = T)
library(pdftools, warn.conflicts = F, quietly = T)
library(purrrlyr, warn.conflicts = F, quietly = T)
library(forcats, warn.conflicts = F, quietly = T)
library(here, warn.conflicts = F, quietly = T)

```



### Select the **Input**

```{r app, echo=FALSE}
# param set
n_word <- 20
n_top <- 150
n_gramming <- 3

## drake task
francia = pdf_text(here("data","francia.pdf")) %>%
  readr::read_lines() %>%  
  str_squish() %>% 
  as_tibble() %>% 
  mutate(paese= forcats::as_factor("francia")) %>% 
  rename(text = value)

germania = pdf_text(here("data","germania.pdf")) %>%
  readr::read_lines() %>%
   str_squish() %>%  
  as_tibble() %>% 
  mutate(paese= forcats::as_factor("germania")) %>% 
  rename(text = value)


## funs 
##

sigmoid <- function(x_from, x_to, y_from, y_to, scale = 5, n = 100) {
  x <- seq(-scale, scale, length = n)
  y <- exp(x) / (exp(x) + 1)
  tibble(x = (x + scale) / (scale * 2) * (x_to - x_from) + x_from,
         y = y * (y_to - y_from) + y_from)
}

egde_lines <- function(trigram, from_word, to_word, scale = 5, n = 50, x_space = 0) {
  
  from_word <- from_word %>%
    select(-n) %>%
    set_names(c("from", "y_from", "x_from"))
  
  to_word <- to_word %>%
    select(-n) %>%
    set_names(c("to", "y_to", "x_to"))
  
  links <- crossing(from = from_word$from, 
                    to = to_word$to) %>%
    mutate(word_pair = paste(from, to),
           number = map_dbl(word_pair, 
                            ~ sum(str_detect(trigram$trigram, .x)))) %>%
    left_join(from_word, by = "from") %>%
    left_join(to_word, by = "to")
  
  links %>%
    by_row(~ sigmoid(x_from = .x$x_from + 0.2 + x_space,
                     x_to = .x$x_to - 0.05, 
                     y_from = .x$y_from, y_to = .x$y_to, 
                     scale = scale, n = n) %>%
    mutate(word_pair = .x$word_pair,
           number = .x$number,
           from = .x$from)) %>%
    pull(.out) %>%
    bind_rows()
}

str_nth_word <- function(x, n, sep = " ") {
 str_split(x, pattern = " ") %>%
 map_chr(~ .x[n])
}
  


country <- c("francia", "germania")

inputPanel(
  
  textInput("prima_parola", "Prima Parola:", "pensions"),
  
  textInput("seconda_parola", "Seconda Parola:", "young"),
  
  selectInput("country", label = "Seleziona Paese", choices = country,
              selected = country[2])
  
  # downloadButton('downloadPlot', 'Download Plot')
  
)

    
start_words  = reactive({ c(input$prima_parola, input$seconda_parola) })

trigrammas <-  germania %>%
  unnest_tokens(trigram, text, token = "ngrams", n = n_gramming)

## top 150 trigrams using count and some regex magi
pattern = reactive({  str_c("^", start_words(), " ", collapse = "|") })

top_words <-  reactive({ trigrammas %>%
 dplyr::filter(str_detect(trigram, pattern())) %>%
 count(trigram, sort = TRUE) %>%
 slice(seq_len(n_top)) %>%
 pull(trigram)
})

trigrams <- reactive({ trigrammas %>%
 dplyr::filter(trigram %in% top_words()) })


nodes <- reactive({ 
  map_df(seq_len(n_gramming),
    ~ trigrams() %>%
        mutate(word = str_nth_word(trigram, .x)) %>%
        count(word, sort = TRUE) %>%
        slice(seq_len(n_word)) %>% 
        mutate(y = seq(from = n_word + 1, to = 0, 
                       length.out = n() + 2)[seq_len(n()) + 1],
               x = .x)) %>% 
    anti_join(get_stopwords(language = "en"))
})


 # egdes between first and second column
egde1 <- reactive({  egde_lines(trigram = trigrams(), 
          from_word = dplyr::filter(nodes(), x == 1), 
          to_word = dplyr::filter(nodes(), x == 2), 
          n = 50) %>%
          dplyr::filter(number > 0) %>%
 mutate(id = word_pair)
})

# Words in second colunm
## That start with he
second_word_he <- reactive({  nodes() %>%
 dplyr::filter(x == 2) %>%
 select(-n) %>%
 left_join(
   trigrams() %>% 
     dplyr::filter(str_nth_word(trigram, 1) ==  start_words()[1]) %>%
     mutate(word = str_nth_word(trigram, 2)) %>%
     count(word), 
   by = "word"
 ) %>%
 replace_na(list(n = 0))
})

## That start with she
second_word_she <-  reactive({ nodes() %>%
 dplyr::filter(x == 2) %>%
 select(-n) %>%
 left_join(
   trigrams() %>% 
     dplyr::filter(str_nth_word(trigram, 1) == start_words()[2]) %>%
     mutate(word = str_nth_word(trigram, 2)) %>%
     count(word), 
   by = "word"
 ) %>%
 replace_na(list(n = 0))
})

# Words in third colunm
## That start with he (stopworded)
third_word_he <-  reactive({ nodes() %>%
 dplyr::filter(x == 3) %>%
 select(-n) %>%
 left_join(
   trigrams() %>% 
     dplyr::filter(str_nth_word(trigram, 1) == start_words()[1]) %>%
     mutate(word = str_nth_word(trigram, 3)) %>%
     count(word), 
   by = "word"
 ) %>%
 replace_na(list(n = 0)) %>%   
 anti_join(get_stopwords(language = "en"))
})

## That start with she (stopworded)
third_word_she <- reactive({  nodes() %>%
 dplyr::filter(x == 3) %>%
 select(-n) %>%
 left_join(
   trigrams() %>% 
     dplyr::filter(str_nth_word(trigram, 1) == start_words()[2]) %>%
     mutate(word = str_nth_word(trigram, 3)) %>%
     count(word), 
   by = "word"
 ) %>%
 replace_na(list(n = 0)) %>%
 anti_join(get_stopwords(language = "en")) 
})

# egdes between second and third column that starts with he
egde2_he <- reactive({ 
  egde_lines(dplyr::filter(trigrams(),
                           str_detect(trigram, paste0("^", start_words()[1], " "))),
             second_word_he(),
             third_word_he(), n = 50) %>%
 mutate(y = y + 0.05,
        from = start_words()[1],
        id = str_c(from, word_pair, sep = " ")) %>%
 dplyr::filter(number > 0)
})

# egdes between second and third column that starts with she
egde2_she <- reactive({  egde_lines(dplyr::filter(trigrams(), 
                             str_detect(trigram, paste0("^", start_words()[2], " "))), 
            second_word_she(), third_word_she(), n = 50) %>%
 mutate(y = y - 0.05,
        from = start_words()[2],
        id = str_c(from, word_pair, sep = " ")) %>%
 dplyr::filter(number > 0)
})
# All edges
# 
edges <- reactive({  bind_rows(egde1(), egde2_he(), egde2_she()) })

# })



renderPlot({
  
  nodes() %>% 
    ggplot(aes(x, y, label = word, size = n)) +
    geom_text(hjust = 0, color = "white") +
    theme_void() +
    geom_line(data = edges(),
              aes(x, y, group = id, color = from, alpha = sqrt(number)),
              inherit.aes = FALSE) +
    guides(alpha = "none", color = "none", size = "none") +
    xlim(c(0.9, 3.2)) +
    scale_size(range = c(3, 8)) +
    scale_color_manual(values = c("#5EF1F1", "red")) +
    theme(plot.background = element_rect(fill ="#1c5253", colour = 'black'),
        text = element_text(color = "#1c5253", size = 15))

})

# output$downloadPlot <- downloadHandler(
#      filename = function() { glue("{input$country}_{Sys.Date()}.pdf")},
#    content = function(file) {
#      ggsave(file,plotInput())
#     }
# )
```

